### ISSUE TITLE
Upload Dependency-Check XML Failed

### ISSUE THREAD

**Issue by vinhduong** [archerysec/archerysec-cli#17]
Hi all,
Could you please help me? 
I have a Dependency-Check XML Report and I use the command to upload report

archerysec-cli -h http://127.0.0.1:8000 -t b-phbNlxOkWPNxwBqrgkwkPZBUfY5kT9DkqGSKXOqG31cM0ggcIrp-W7ozcRyH5C --upload --path=/opt/deploy/dpreport20230816.xml --file-type=XML --target=ASFLKSF --scanner=dependencycheck --project=75d730ea-d593-4fca-b416-7f1d028e4df6 

And the error message here:

Copyright (C) 2023 ArcherySec CLI v3.1.14 
Traceback (most recent call last):
  File "/usr/local/bin/archerysec-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/archerysec_cli/cli/cli.py", line 468, in main
    scan_action()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/archerysec_cli/cli/cli.py", line 108, in scan_action
    upload_report(
  File "/usr/local/lib/python3.9/dist-packages/archerysec_cli/cli/cli.py", line 253, in upload_report
    scan_data = archerysec.xml_upload(file=report_path)
  File "/usr/local/lib/python3.9/dist-packages/archerysec_cli/util/api.py", line 84, in xml_upload
    return send_request.json()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I try to use ArcherySec (Web Portal) to upload "dpreport20230816.xml" and it's successfully. I try download the template report from here [https://raw.githubusercontent.com/archerysec/report-sample/main/Dependency-check/dependency-check-report_v5.2.1.xml](https://raw.githubusercontent.com/archerysec/report-sample/main/Dependency-check/dependency-check-report_v5.2.1.xml) but I got the same results. Please help me.

archerysec-cli FAILED
Acherysec - WebPortal - OK

**Comment by anandtiwarics** [comment]
fixed https://github.com/archerysec/archerysec/pull/630
